summarizer_project/inference_engine/urls.py
from django.urls import path

from . import views

app_name = 'inference_engine'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('<int:dataset_id>', views.index, name='index'),
    path('dataset-list', views.dataset_list, name='dataset-list'),
    path('dataset-process', views.action_step_datasets, name='dataset-process'),
    path('dataset-process/<int:dataset_id>', views.action_step_datasets, name='dataset-process'),
    path('sentence-label', views.pairing_sentence_label, name='sentence-label'),
    path('display-training-dataset/<int:dataset_id>', views.display_training_dataset, name='display-training-dataset'),
    path('sentence-munging', views.sentence_munging, name='sentence-munging'),
    path('sentence-munging/<int:dataset_id>', views.display_sentence_munging, name='display-sentence-munging'),
    path('sentence-scoring', views.sentence_scoring, name='sentence-scoring'),
    path('sentence-scoring/<int:dataset_id>', views.display_sentence_scoring, name='display-sentence-scoring'),
    path('feature-scaling', views.feature_scaling, name='feature-scaling'),
    path('feature-scaling/<int:dataset_id>', views.display_feature_scaling, name='display-feature-scaling'),
    path('proceed-bagging', views.proceed_bagging, name='proceed-bagging'),
    path('random-forest', views.random_forest, name='random-forest'),
    path('upload-test-dataset', views.upload_test_dataset, name='upload-test-dataset'),
    path('summarize-article/<int:article_id>', views.summarize_article, name='summarize-article'),
    path('update-rule/<int:rule_id>', views.update_rule, name='update-rule'),
    path('evalute-oob', views.get_accuracy_from_oob, name='evaluate-oob'),
    path('evalute-article/<int:dataset_id>', views.test_generate_summary, name='evaluate-article'),
    path('evalute-dataset/<int:dataset_id>', views.test_generate_summaries, name='evaluate-dataset'),
    path('testing-statistics/<int:dataset_id>', views.proceed_statistics, name='testing-statistics'),
]

summarizer_project/summarizer_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inference_engine.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

summarizer_project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Summarizer | {% block title %}{% endblock %}</title>

</head>

<body>
    
    <div class="container">
        {% include 'partials/_navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

summarizer_project/templates/inference-base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-web/css/all.css' %}">
    <!-- Add Card -->
    <link rel="stylesheet" href="{% static 'css/card-deck.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block optcss %}{% endblock %}
    <title>Summarizer | {% block title %}{% endblock %}</title>
</head>

<body>

    <div class="container mt-3">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #243665;">
            {% block uploadarticle %}
            {% endblock %}
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'inference_engine:index' %}"><span class="menu-bg-color">Summarizer</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'inference_engine:dataset-list' %}"><span class="menu-bg-color">Training</span></a>
                </li>
                {% block selectrules %}
                {% endblock %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block optjs %}
    {% endblock %}
</body>

</html>