summarizer_project/inference_engine/urls.py
from django.urls import path

from . import views

app_name = 'inference_engine'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('<int:dataset_id>', views.index, name='index'),
    path('dataset-list', views.dataset_list, name='dataset-list'),
    path('dataset-process', views.action_step_datasets, name='dataset-process'),
    path('dataset-process/<int:dataset_id>', views.action_step_datasets, name='dataset-process'),
    path('sentence-label', views.pairing_sentence_label, name='sentence-label'),
    path('display-training-dataset/<int:dataset_id>', views.display_training_dataset, name='display-training-dataset'),
    path('sentence-munging', views.sentence_munging, name='sentence-munging'),
    path('sentence-munging/<int:dataset_id>', views.display_sentence_munging, name='display-sentence-munging'),
    path('sentence-scoring', views.sentence_scoring, name='sentence-scoring'),
    path('sentence-scoring/<int:dataset_id>', views.display_sentence_scoring, name='display-sentence-scoring'),
    path('feature-scaling', views.feature_scaling, name='feature-scaling'),
    path('feature-scaling/<int:dataset_id>', views.display_feature_scaling, name='display-feature-scaling'),
    path('proceed-bagging', views.proceed_bagging, name='proceed-bagging'),
    path('random-forest', views.random_forest, name='random-forest'),
    path('upload-test-dataset', views.upload_test_dataset, name='upload-test-dataset'),
    path('summarize-article/<int:article_id>', views.summarize_article, name='summarize-article'),
    path('update-rule/<int:rule_id>', views.update_rule, name='update-rule'),
    path('evalute-oob', views.get_accuracy_from_oob, name='evaluate-oob'),
    path('evalute-article/<int:dataset_id>', views.test_generate_summary, name='evaluate-article'),
    path('evalute-dataset/<int:dataset_id>', views.test_generate_summaries, name='evaluate-dataset'),
    path('testing-statistics/<int:dataset_id>', views.proceed_statistics, name='testing-statistics'),
]

summarizer_project/summarizer_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inference_engine.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

summarizer_project/inference_engine/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponseRedirect
from .models import DatasetSources, OriginalDataset, AggregateResource, TestingDatasetSources, TestingOriginalDataset, SelectedRule, LogProcess, SummaryEvaluation
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .functionality.sentence_domain import read_json_line, iterate_filedecorator, saved_originaldataset, \
    echo_sentence_label_pairing, SentenceMunging, SentenceScoring, dataset_into_dataframe, ComprehendDataset, \
    dataframe_into_csv, dataframe_into_database, Bagging, RandomForest, save_rules, saved_test_originaldataset, \
    concat_tokens_tosentence, evaluate_oob, extract_ground_truth, article_rouge_evaluation, proceed_rouge_evaluation
import os
import json
import socket
from django.urls import reverse
from os import listdir, makedirs
import pandas as pd
from time import time
import datetime
from natsort import natsorted
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
dataset_dir = "/summarizer_project/static/"

global_context = {}

def index(request, dataset_id="none"):
    check_dataset = TestingDatasetSources.objects.all()
    if not check_dataset:
        return render(request, 'inference_engine/index.html', {
            "dataset_empty": True
        })
    if dataset_id != "none":
        dataset_res = TestingDatasetSources.objects.get(pk=dataset_id)
    else:
        dataset_id = TestingDatasetSources.objects.all()[0].id
        dataset_res = TestingDatasetSources.objects.get(pk=dataset_id)
    original_datasets = dataset_res.testingoriginaldataset_set.all()
    ids = []
    categories = []
    titles = []
    contents = []
    extractive_summaries = []
    sources = []
    source_urls = []
    for original_dataset in original_datasets:
        raw_jsonline = json.loads(original_dataset.json_line)
        ids.append(original_dataset.id)
        categories.append(original_dataset.category)
        titles.append(original_dataset.title)
        contents.append(concat_tokens_tosentence(raw_jsonline['paragraphs']))
        sources.append(original_dataset.source)
        source_urls.append(raw_jsonline['source_url'])
        extractive_summaries.append(original_dataset.reference_summary)
    compact_articles = zip(ids, categories, titles, contents, sources, source_urls, extractive_summaries)
    paginator = Paginator(list(compact_articles), 6)
    page = request.GET.get('page')
    paged_article = paginator.get_page(page)
    available_datasets = TestingDatasetSources.objects.all()
    context = {
        "dataset_empty": False,
        "compact_articles": paged_article,
        "available_datasets": available_datasets,
        "last_page": paginator.num_pages,
        "dataset_res": dataset_res,
        "is_evaluate": dataset_res.is_evaluate
    }
    return render(request, 'inference_engine/index.html', context)


def dataset_list(request):
    if request.method == 'POST':
        uploaded_file = request.FILES['rawdataset']
        print(uploaded_file.name)
        print(uploaded_file.size)
        rawdataset = DatasetSources(path=uploaded_file)
        rawdataset.save()
        filename = f"{uploaded_file.name}-{rawdataset.id}"
        file_path = BASE_DIR + dataset_dir + str(rawdataset.path)
        lines_injson = read_json_line(file_path)
        count_lines = iterate_filedecorator(lines_injson)
        DatasetSources.objects.filter(pk=rawdataset.id).update(title=filename)
        DatasetSources.objects.filter(pk=rawdataset.id).update(total_articles=count_lines)
        saved_originaldataset(rawdataset, file_path, count_lines)
    rules = AggregateResource.objects.all()
    context = {
        'dataset_sources': DatasetSources.objects.all(),
        'rules': rules
    }
    return render(request, 'inference_engine/dataset_list.html', context)


def action_step_datasets(request, dataset_id=''):
    if request.method == 'POST':
        dataset_id = request.POST['dataset_id']
        dataset_res = DatasetSources.objects.get(pk=dataset_id)
        if dataset_res.is_evaluate_oob:
            context = {
                'dataset_res': dataset_res,
                'accuracy_oob': round(dataset_res.aggregateresource.accuracy_oob, 2)
            }
        else:
            context = {
                'dataset_res': dataset_res
            }
    else:
        dataset_id = dataset_id
        dataset_res = DatasetSources.objects.get(pk=dataset_id)
        context = {
            'dataset_res': dataset_res
        }
    return render(request, 'inference_engine/action_step.html', context)


def pairing_sentence_label(request):
    if request.method == 'POST':
        start = time()

        dataset_id = request.POST['dataset_id']
        dataset_res = DatasetSources.objects.get(pk=dataset_id)
        original_datasets = dataset_res.originaldataset_set.all()
        for original_dataset in original_datasets:
            article = json.loads(original_dataset.json_line)
            results = echo_sentence_label_pairing(article
                                                  ['paragraphs'], article['gold_labels'])
            for result in results:
                related_originaldataset = OriginalDataset.objects.get(pk=original_dataset.id)
                related_originaldataset.trainingdataset_set.create(sentence_token=result[0], sentence=result[1],
                                                                   label=result[2])
        DatasetSources.objects.filter(pk=dataset_res.id).update(is_originaldatasetpair=True)
        global_context = {
            'dataset_res': dataset_res
        }

        ground_truth = extract_ground_truth(dataset_id)
        DatasetSources.objects.filter(pk=dataset_res.id).update(ground_truth=ground_truth)

        end = time()
        result = end-start
        print(f"inference_engine:pairing_sentence_label takes = {str(datetime.timedelta(seconds=result))}")

        return HttpResponseRedirect(reverse('inference_engine:dataset-process', args=[dataset_id]))


def display_training_dataset(request, dataset_id):
    if request.method == 'GET':
        start = time()

        dataset_res = DatasetSources.objects.get(pk=dataset_id)
        original_datasets = dataset_res.originaldataset_set.all()
        sentence_tokens = []
        sentences = []
        labels = []
        for original_dataset in original_datasets[::-1]:
            related_original_dataset = OriginalDataset.objects.get(pk=original_dataset.id)
            training_datasets = related_original_dataset.trainingdataset_set.all()
            for training_dataset in training_datasets:
                sentence_tokens.append(training_dataset.sentence_token)
                sentences.append(training_dataset.sentence)
                labels.append(training_dataset.label)
        compact_sentences = zip(sentences, sentence_tokens, labels)
        paginator = Paginator(list(compact_sentences), 20)
        page = request.GET.get('page')
        paged_sentences = paginator.get_page(page)
        context = {
            "compact_sentences": paged_sentences,
            "last_page": paginator.num_pages
        }

        end = time()
        result = end-start
        print(f"inference_engine:display_training_dataset takes = {str(datetime.timedelta(seconds=result))}")
        return render(request, 'inference_engine/display_trainingdata.html', context)


def sentence_munging(request):
    if request.method == 'POST':
        start = time()

        dataset_id = request.POST['dataset_id']
        dataset_res = DatasetSources.objects.get(pk=dataset_id)
        original_datasets = dataset_res.originaldataset_set.all()
        for original_dataset in original_datasets:
            article = json.loads(original_dataset.json_line)
            results = echo_sentence_label_pairing(article['paragraphs'], article['gold_labels'])
            for result in results:
                related_originaldataset = OriginalDataset.objects.get(pk=original_dataset.id)
                sentence_munging = SentenceMunging(result[0])
                related_originaldataset.preprocesstrainingdataset_set.create(sentence_token=sentence_munging.tokens,
                                                                             sentence=result[1], label=result[2])
        DatasetSources.objects.filter(pk=dataset_id).update(is_preprocessing=True)

        end = time()
        result = end-start
        print(f"inference_engine:sentence_munging takes = {str(datetime.timedelta(seconds=result))}")
        return HttpResponseRedirect(reverse('inference_engine:dataset-process', args=[dataset_id]))


def display_sentence_munging(request, dataset_id):
    if request.method == 'GET':
        start = time()

        dataset_res = DatasetSources.objects.get(pk=dataset_id)
        original_datasets = dataset_res.originaldataset_set.all()
        sentence_tokens = []
        sentences = []
        labels = []
        for original_dataset in original_datasets[::-1]:
            related_original_dataset = OriginalDataset.objects.get(pk=original_dataset.id)
            training_datasets = related_original_dataset.preprocesstrainingdataset_set.all()
            for training_dataset in training_datasets:
                sentence_tokens.append(training_dataset.sentence_token)
                sentences.append(training_dataset.sentence)
                labels.append(training_dataset.label)
        compact_sentences = zip(sentences, sentence_tokens, labels)
        paginator = Paginator(list(compact_sentences), 20)
        page = request.GET.get('page')
        paged_sentences = paginator.get_page(page)
        context = {
            "compact_sentences": paged_sentences,
            "last_page": paginator.num_pages
        }

        end = time()
        result = end-start

summarizer_project/templates/inference_engine/action_step.html
{% extends 'inference-base.html' %}
{% load static %}
{% block optcss %}
<link rel="stylesheet" href="{% static 'css/event_list.css' %}">
{% endblock %}
{% block title %}Dataset Process{% endblock %}
{% block content %}
<div id="action-step-card" class="row mt-3 ml-5 mr-5 d-flex justify-content-center">
    <div class="col-md-12">
        <ul class="event-list ml-5 mr-5">
            {% if dataset_res %}
                <li class="mb-4">
                    <time>
                        <span class="day mt-3">01</span>
                        <span class="month">Step</span>
                    </time>
                    <div class="info">
                        <h2 class="title mt-3">Create Sentence Label Pair</h2>
                        <p class="desc">Provid sentence and label pairing with the manual extractive summarization</p>
                        {% if dataset_res.is_originaldatasetpair %}
                            <a href="{% url 'inference_engine:display-training-dataset' dataset_res.id %}" class="btn btn-outline-success ml-2 mt-1" target="_blank">Display The Result</a>
                        {% else %}
                            <form action="{% url 'inference_engine:sentence-label' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="dataset_id" value="{{ dataset_res.id }}">
                                <button class="btn btn-outline-primary ml-2 mt-1">Execute The Process</button>
                            </form>
                        {% endif %}
                    </div>
                </li>
                <li class="mb-4">
                    <time>
                        <span class="day mt-3">02</span>
                        <span class="month">Step</span>
                    </time>
                    <div class="info">
                        <h2 class="title mt-3">Sentence Munging</h2>
                        <p class="desc">Remove Punctuations, Case Folding, Remove Stopword, Lemmatization</p>
                        {% if not dataset_res.is_originaldatasetpair %}
                            <button class="btn btn-outline-dark mt-2 ml-2" disabled>Execute By Order</button>
                        {% else %}
                            {% if dataset_res.is_preprocessing %}
                                <a href="{% url 'inference_engine:display-sentence-munging' dataset_res.id %}" class="btn btn-outline-success ml-2 mt-1" target="_blank">Display The Result</a>
                            {% else %}
                                <form action="{% url 'inference_engine:sentence-munging' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="dataset_id" value="{{ dataset_res.id }}">
                                    <button class="btn btn-outline-primary ml-2 mt-1">Execute The Process</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </li>
                <li class="mb-4">
                    <time>
                        <span class="day mt-3">03</span>
                        <span class="month">Step</span>
                    </time>
                    <div class="info">
                        <h2 class="title mt-1">Sentence Scoring</h2>
                        <p class="desc">Word Frequency, Title Similarity, Sentence Position, Sentence Length, Numerical Token, TF-ISF, Cosine Similarity, Bi-Gram, Tri-Gram</p>
                        {% if not dataset_res.is_preprocessing %}
                            <button class="btn btn-outline-dark mt-2 ml-2" disabled>Execute By Order</button>
                        {% else %}
                            {% if dataset_res.is_sentencescoring %}
                                <a href="{% url 'inference_engine:display-sentence-scoring' dataset_res.id %}" class="btn btn-outline-success ml-2 mt-1" target="_blank">Display The Result</a>
                            {% else %}
                                <form action="{% url 'inference_engine:sentence-scoring' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="dataset_id" value="{{ dataset_res.id }}">
                                    <button class="btn btn-outline-primary ml-2 mt-1">Execute The Process</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </li>
                <li class="mb-4">
                    <time>
                        <span class="day mt-3">04</span>
                        <span class="month">Step</span>
                    </time>
                    <div class="info">
                        <h2 class="title mt-3">Feature Scaling</h2>
                        <p class="desc">Handling Missing Values, Remove Outliers, MinMaxScaler</p>
                        {% if not dataset_res.is_sentencescoring %}
                            <button class="btn btn-outline-dark mt-2 ml-2" disabled>Execute By Order</button>
                        {% else %}
                            {% if dataset_res.is_scale_sentencescoring %}
                                <a href="{% url 'inference_engine:display-feature-scaling' dataset_res.id %}" class="btn btn-outline-success ml-2 mt-1" target="_blank">Display The Result</a>
                            {% else %}
                                <form action="{% url 'inference_engine:feature-scaling' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="dataset_id" value="{{ dataset_res.id }}">
                                    <button class="btn btn-outline-primary ml-2 mt-1">Execute The Process</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </li>
                <li class="mb-4">
                    <time>
                        <span class="day mt-3">05</span>
                        <span class="month">Step</span>
                    </time>
                    <div class="info">
                        <h2 class="title mt-3">Bootstrap Aggregating</h2>
                        <p class="desc">Preparing 100 Bags and 100 Out-Of-Bags(OOB) Training Dataset</p>
                        {% if not dataset_res.is_scale_sentencescoring %}
                            <button class="btn btn-outline-dark mt-2 ml-2" disabled>Execute By Order</button>
                        {% else %}
                            {% if dataset_res.is_bagging %}
                                <button class="btn btn-outline-dark mt-2 ml-2" disabled>Done Processing</button>
                            {% else %}
                                <form action="{% url 'inference_engine:proceed-bagging' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="dataset_id" value="{{ dataset_res.id }}">
                                    <button class="btn btn-outline-primary ml-2 mt-1">Execute The Process</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </li>
                <li class="mb-4">
                    <time>
                        <span class="day mt-3">06</span>
                        <span class="month">Step</span>
                    </time>
                    <div class="info">
                        <h2 class="title mt-3">Random Forest</h2>
                        <p class="desc">Train 100 Bags Training Dataset Using C4.5 Classifier</p>
                        {% if not dataset_res.is_bagging %}
                            <button class="btn btn-outline-dark mt-2 ml-2" disabled>Execute By Order</button>
                        {% else %}
                            {% if dataset_res.is_randomforest %}
                                <button class="btn btn-outline-dark mt-2 ml-2" disabled>Done Processing</button>
                            {% else %}
                                <form action="{% url 'inference_engine:random-forest' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="dataset_id" value="{{ dataset_res.id }}">
                                    <button class="btn btn-outline-primary ml-2 mt-1">Execute The Process</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </li>
                <li class="mb-4">
                    <time>
                        <span class="day mt-3">07</span>
                        <span class="month">Step</span>
                    </time>
                    <div class="info">
                        <h2 class="title mt-3">Evaluate OOB</h2>
                        <p class="desc">Look for accuracy from Out-Of-Bags Dataset</p>
                        {% if not dataset_res.is_randomforest %}
                            <button class="btn btn-outline-dark mt-2 ml-2" disabled>Execute By Order</button>
                        {% else %}
                            {% if dataset_res.is_evaluate_oob %}
                                <p class="mt-1 ml-2">
                                    Accuracy of OOB evaluation : <strong>{{ accuracy_oob }}</strong>
                                </p>
                            {% else %}
                                <form action="{% url 'inference_engine:evaluate-oob' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="dataset_id" value="{{ dataset_res.id }}">
                                    <button class="btn btn-outline-primary ml-2 mt-1">Execute The Process</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                </li>
            {% else %}
                <p>Dataset did not exist</p>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}

summarizer_project/templates/inference_engine/index.html
{% extends 'inference-base.html' %}
{% load static %}
{% block optcss %}
<link rel="stylesheet" href="{% static 'css/index_inference.css' %}">
{% endblock %}
{% block title %}Inference Engine{% endblock %}
{% block uploadarticle %}
<!-- Upload Article Navigation -->
<form action="{% url 'inference_engine:upload-test-dataset' %}" method="post" enctype="multipart/form-data" class="mt-2">
    {% csrf_token %}
    <div class="upload-btn-wrapper ml-2">
        <button class="btn">Select Dataset For Testing</button>
        <input type="file" name="testdataset"/>
        <!-- <button class="btn ml-2 mr-2">Upload Dataset</button> -->
    </div>
    <div class="upload-btn-wrapper ml-2">
        <button class="btn">Upload Dataset</button>
    </div>
</form>
<div class="btn-group ml-3">
    <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        Available Dataset
    </button>
    <div class="dropdown-menu">
        {% if available_datasets %}
            {% for available_dataset in available_datasets %}
                <a class="dropdown-item" href="{% url 'inference_engine:index' available_dataset.id %}">{{ available_dataset.title }}</a>
            {% endfor %}
        {% else %}
            <a class="dropdown-item" href="#">Empty Dataset</a>
        {% endif %}
    </div>
</div>
{% if dataset_res %}
    {% if not is_evaluate %}
        <div class="upload-btn-wrapper ml-2">
            <a href="{% url 'inference_engine:evaluate-dataset' dataset_res.id %}" class="btn">Summary Evaluation</a>
        </div>
    {% else %}
    <div class="upload-btn-wrapper ml-2">
        <a href="{% url 'inference_engine:testing-statistics' dataset_res.id %}" class="btn" target="_blank">Statistics</a>
    </div>
    {% endif %}
{% endif %}
{% endblock %}

{% block content %}

    <!-- Card -->
    <div class="social-box">
        <div class="container">
            <div class="row">
                {% if dataset_empty %}
                    <div class="col-lg-4 col-xs-12 text-center">
                        <div class="box">
                            <i class="far fa-newspaper fa-3x" aria-hidden="true"></i>
                            <div class="box-title">
                                <h3>Empty Dataset</h3>
                            </div>
                            <div class="box-text">
                                <span>Lorem ipsum dolor sit amet, id quo eruditi eloquentiam. Assum decore te sed. Elitr scripta
                                    ocurreret qui ad.</span>
                            </div>
                            <div class="box-btn">
                                <a href="#">Learn More</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    {% if compact_articles %}
                        {% for id, category, title, content, source, source_url, summary in compact_articles %}
                            <div class="col-lg-4 col-xs-12 text-center">
                                <div class="box">
                                    <i class="far fa-newspaper fa-3x" aria-hidden="true"></i>
                                    <div class="box-title">
                                        <h3> <a href="{{ source_url }}" target="_blank">{{ source }}</a> </h3>
                                    </div>
                                    <div class="box-text">
                                        <span>{{ title }}</span>
                                    </div>
                                    <div class="box-btn">
                                        <a href="{% url 'inference_engine:summarize-article' id %}" target="_blank">Article Sumarizer</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <!-- End Card -->

    <!-- Pagination -->
    {% if not dataset_empty %}
        <div class="row">
            <div class="col-md-12 ml-3">
                {% if compact_articles.has_other_pages %}
                    <ul class="pagination">
                        <!-- Link To Go Back to Previous Page -->
                        {% if compact_articles.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ compact_articles.previous_page_number }}" class="page-link">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disable">
                                <a class="page-link">&laquo;</a>
                            </li>
                        {% endif %}
                        {% if last_page > 10 %}
                            <!-- Loop Through Page Range -->
                            {% for i in compact_articles.paginator.page_range %}
                                {% if compact_articles.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link">{{ i }}</a>
                                    </li>
                                {% elif i <= compact_articles.number|add:9 and i >= compact_articles.number|add:-8 %}
                                    {% if i != last_page %}
                                        <li class="page-item">
                                            <a href="?page={{i}}" class="page-link">{{i}}</a>
                                        </li>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                            <!-- Link To Go Back to Previous Page -->
                            {% if compact_articles.has_next %}
                                <li class="page-item disable">
                                    <a class="page-link">...</a>
                                </li>
                                <li class="page-item">
                                    <a href="?page={{last_page}}" class="page-link">{{last_page}}</a>
                                </li>
                                <li class="page-item">
                                    <a href="?page={{compact_articles.next_page_number}}" class="page-link">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="" class="page-link disable">&raquo;</a>
                                </li>
                            {% endif %}
                        {% else %}
                            <!-- Loop Through Page Range -->
                            {% for i in compact_articles.paginator.page_range %}
                                {% if compact_articles.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link">{{ i }}</a>
                                    </li>
                                {% elif i <= compact_articles.number|add:20 and i >= compact_articles.number|add:-20 %}
                                    <li class="page-item">
                                        <a href="?page={{i}}" class="page-link">{{i}}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            <!-- Link To Go Back to Previous Page -->
                            {% if compact_articles.has_next %}
                                <li class="page-item">
                                    <a href="?page={{compact_articles.next_page_number}}" class="page-link">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a href="" class="page-link disable">&raquo;</a>
                                </li>
                            {% endif %}
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    {% endif %}
    <!-- End Pagination -->

{% endblock %}